# Syntax highlighting
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title: "Unblocked Games"
description: "Play a wide range of unblocked games online. Enjoy an ad-free experience."
keywords: "unblocked games, free games, browser games, play games, unblocked games 76"
author: "Your Name"

