# Syntax highlighting
highlighter:         pygments
# Setup
title: "Unblocked Games"
description: "Play a wide range of unblocked games online. Enjoy an ad-free experience."
keywords: "unblocked games, free games, browser games, play games, unblocked games 76"
author: "Your Name"

